const c=document.querySelector('#c'),ctx=c.getContext('2d'),scrub=document.querySelector('#s'),timeOut=document.querySelector('#t'),dataEl=document.querySelector('#d'),play=document.querySelector('#p'),reset=document.querySelector('#r'),err=document.querySelector('#err');
const W=1920,H=1080,CARD_W=470,PITCH=477,ART_H=872,TITLE_Y=872,TITLE_H=92,DESC_Y=965,DESC_H=110;
const BORDER='#0b0b0b',TITLE_BG='rgb(242,242,242)',DESC_BG='rgb(100,97,88)',BADGE_RED='rgb(194,0,11)',STEADY_SPEED=133.3,HERO_TRIGGER_X=1472;
const sample=[
 {title:'In A Freezer',value:'50K',unit:'YEARS',description:'Freezing stops bacteria from moving, preserving your hand',art:'#218fce'},
 {title:"Mars' Atmosphere",value:'10K',unit:'YEARS',description:'Frozen, airless and bone-dry – it mummifies you',art:'#d9491d'},
 {title:'Outside A Plane Mid-Flight',value:'5K',unit:'YEARS',description:'Freezing wind slowly grinds the frozen flesh away',art:'#2b9ee3'},
 {title:'Toothpaste',value:'8',unit:'MONTHS',description:'Mild abrasives slowly wear the skin and flesh away',art:'#36a5de'},
 {title:"World's Spiciest Hot Sauce",value:'6',unit:'MONTHS',description:'Vinegar and chilli oils attack the skin barrier',art:'#171313'},
 {title:'Sea Water',value:'5',unit:'MONTHS',description:'Salt and brine slowly break the flesh down',art:'#20aee5'},
 {title:'Dishwasher Detergent',value:'4',unit:'MONTHS',description:'The alkaline cleaner steadily attacks tissue',art:'#e9a51b'},
 {title:'Mud',value:'3',unit:'MONTHS',description:'Moisture and microbes steadily damage exposed tissue',art:'#7a5434'}
];
dataEl.value=JSON.stringify(sample,null,2);
let playing=false,wall0=0,t0=0;
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v)),lerp=(a,b,t)=>a+(b-a)*t;
const smooth=v=>{v=clamp(v);return v*v*(3-2*v)};
const outCubic=v=>1-Math.pow(1-clamp(v),3);
function data(){try{err.textContent='';return JSON.parse(dataEl.value)}catch(e){err.textContent=e.message;return sample}}
function shade(hex,amt){const m=/^#?([0-9a-f]{6})$/i.exec(hex);if(!m)return hex;let n=parseInt(m[1],16),r=clamp((n>>16)+amt,0,255),g=clamp(((n>>8)&255)+amt,0,255),b=clamp((n&255)+amt,0,255);return `rgb(${r},${g},${b})`}
function wrapText(text,maxWidth,maxLines=2){const words=String(text||'').split(/\s+/);const lines=[];let line='';for(const w of words){const test=line?line+' '+w:w;if(ctx.measureText(test).width<=maxWidth||!line)line=test;else{lines.push(line);line=w;if(lines.length===maxLines-1)break}}if(line&&lines.length<maxLines)lines.push(line);return lines}
function wrapCentered(text,x,y,lineHeight){for(const line of String(text).split('\n')){ctx.fillText(line,x,y);y+=lineHeight}}
function cardGradient(card,x){const g=ctx.createLinearGradient(x,0,x+CARD_W,ART_H);g.addColorStop(0,card.art||'#2689c7');g.addColorStop(1,shade(card.art||'#2689c7',-22));return g}
function drawCredit(x){ctx.save();ctx.fillStyle='#202020';ctx.fillRect(x,5,CARD_W,1070);ctx.fillStyle='#fff';ctx.textAlign='center';ctx.font='500 19px Nunito,sans-serif';wrapCentered('The values presented are estimates\nfrom publicly available\nsources. Individual results may\nvary depending\non concentration, temperature,\nexposure time, and\nother factors. Do not attempt\nany experiments.',x+CARD_W/2,27,25);ctx.strokeStyle='#ddd';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(x+58,200);ctx.lineTo(x+CARD_W-58,200);ctx.stroke();ctx.font='800 51px Nunito,sans-serif';ctx.fillText('Credits',x+CARD_W/2,307);ctx.font='700 24px Nunito,sans-serif';const lines=['Lead Research & Sourcing','Ahmed','','Independent Fact Check','Alex Lambert','','Lead Graphic Designer','Jack H','','Edit & Post-Production','Alex Pacheco','','Thumbnail Designer','Diego Garcia','','Video Idea & Quality Check','Ideaguys.co'];let y=370;for(const line of lines){if(!line){y+=16;continue}ctx.fillText(line,x+CARD_W/2,y);y+=31}ctx.font='500 12px Nunito,sans-serif';wrapCentered('DISCLAIMER:\nTHIS VIDEO IS BASED ON\nCOMMUNITY DISCUSSIONS\nAND RELEVANT SOURCES.',x+CARD_W/2,888,14);ctx.restore()}
function drawCardBase(card,x){ctx.save();ctx.beginPath();ctx.rect(x,5,CARD_W,1070);ctx.clip();ctx.fillStyle=cardGradient(card,x);ctx.fillRect(x,5,CARD_W,ART_H-5);
 // Artwork is still a placeholder layer; geometry/text/badge motion are measured independently.
 ctx.globalAlpha=.16;for(let k=0;k<7;k++){ctx.fillStyle=k%2?'#fff':'#000';ctx.beginPath();ctx.arc(x+55+k*66,500+(k%3)*58,55+(k%2)*25,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;
 ctx.fillStyle=TITLE_BG;ctx.fillRect(x,TITLE_Y,CARD_W,TITLE_H);ctx.fillStyle=DESC_BG;ctx.fillRect(x,DESC_Y,CARD_W,DESC_H);
 ctx.textAlign='center';ctx.fillStyle='#090909';ctx.font='900 42px Nunito,sans-serif';const titleLines=wrapText(card.title,CARD_W-30,2),titleBase=titleLines.length===1?931:905;titleLines.forEach((ln,j)=>ctx.fillText(ln,x+CARD_W/2,titleBase+j*39));
 ctx.fillStyle='#fff';ctx.font='700 25px Nunito,sans-serif';const descLines=wrapText(card.description,CARD_W-50,2),descBase=descLines.length===1?1028:1012;descLines.forEach((ln,j)=>ctx.fillText(ln,x+CARD_W/2,descBase+j*29));ctx.restore();
 ctx.fillStyle=BORDER;ctx.fillRect(Math.round(x+CARD_W),0,7,H)}
function hexPath(cx,top,w,h){ctx.beginPath();ctx.moveTo(cx,top);ctx.lineTo(cx+w/2,top+h*.25);ctx.lineTo(cx+w/2,top+h*.75);ctx.lineTo(cx,top+h);ctx.lineTo(cx-w/2,top+h*.75);ctx.lineTo(cx-w/2,top+h*.25);ctx.closePath()}
function badgeText(card,cx,top,w,h,alpha=1,blur=0){ctx.save();ctx.globalAlpha*=alpha;if(blur)ctx.filter=`blur(${blur}px)`;ctx.fillStyle='#fff';ctx.textAlign='center';ctx.textBaseline='middle';ctx.shadowColor='rgba(0,0,0,.42)';ctx.shadowBlur=Math.max(5,w*.023);ctx.shadowOffsetY=Math.max(4,w*.018);ctx.font=`900 ${Math.round(w*.27)}px Nunito,sans-serif`;ctx.fillText(String(card.value||''),cx,top+h*.43);ctx.font=`800 ${Math.round(w*.13)}px Nunito,sans-serif`;if(card.unit)ctx.fillText(String(card.unit),cx,top+h*.64);ctx.restore()}
function badgeShine(cx,top,w,h,q,opacity=.34){if(q<=0||q>=1)return;ctx.save();hexPath(cx,top,w,h);ctx.clip();ctx.translate(cx,top+h/2);ctx.rotate(-Math.PI/3);const travel=w*2.1,pos=lerp(-travel*.55,travel*.55,smooth(q));const band=58;const g=ctx.createLinearGradient(pos-band,0,pos+band,0);g.addColorStop(0,'rgba(255,255,255,0)');g.addColorStop(.42,`rgba(255,255,255,${opacity*.45})`);g.addColorStop(.5,`rgba(255,255,255,${opacity})`);g.addColorStop(.58,`rgba(255,255,255,${opacity*.45})`);g.addColorStop(1,'rgba(255,255,255,0)');ctx.fillStyle=g;ctx.fillRect(-w*1.8,-h*1.8,w*3.6,h*3.6);ctx.restore()}
function drawBadgeVisual(card,cx,top,w,opt={}){const h=w*1.15;ctx.save();ctx.shadowColor='rgba(0,0,0,.38)';ctx.shadowBlur=Math.max(12,w*.055);ctx.shadowOffsetY=Math.max(7,w*.035);const grad=ctx.createLinearGradient(cx-w/2,top,cx+w/2,top+h);grad.addColorStop(0,'#d0000e');grad.addColorStop(.55,BADGE_RED);grad.addColorStop(1,'#b5000a');ctx.fillStyle=grad;hexPath(cx,top,w,h);ctx.fill();ctx.shadowColor='transparent';badgeText(card,cx,top,w,h,opt.textAlpha??1,opt.blur??0);if(opt.shineQ!=null)badgeShine(cx,top,w,h,opt.shineQ,opt.shineOpacity??.34);ctx.restore()}
function tier(rank){const t=window.RIBBON_STEADY_BADGE?.tiers||[{w:325,top:16},{w:300,top:33},{w:275,top:50},{w:250,top:67}];return t[Math.min(Math.max(rank,0),t.length-1)]}
function sampledFallTop(age){const cfg=window.RIBBON_STEADY_BADGE;if(!cfg?.fallTop?.length)return lerp(-268,16,outCubic(age/.8));const f=age*cfg.fps;if(f<=0)return cfg.fallTop[0];if(f>=cfg.fallTop.length-1)return cfg.fallTop.at(-1);const i=Math.floor(f),q=f-i;return lerp(cfg.fallTop[i],cfg.fallTop[i+1],q)}
function openingBadgeStarts(i){return [.55,2.20,4.20,6.55][i]??99}
function latestOpeningHero(sec,max){let hero=-1;for(let i=0;i<=max;i++)if(sec>=openingBadgeStarts(i))hero=i;return hero}
function drawOpeningBadges(list,states,sec){const hero=latestOpeningHero(sec,Math.min(3,list.length-1));if(hero<0)return;const heroAge=sec-openingBadgeStarts(hero),q=smooth(heroAge/.48);for(let i=0;i<=hero;i++){const st=states[i];if(!st?.visible)continue;const rank=hero-i,now=tier(rank),before=tier(Math.max(0,rank-1));let w=rank===0?325:lerp(before.w,now.w,q),top=rank===0?sampledFallTop(heroAge):lerp(before.top,now.top,q);if(hero===0&&i===0)w=lerp(338,325,clamp(heroAge/1.3));const blur=rank===0?lerp(13,0,smooth((heroAge-.45)/.62)):0,textAlpha=rank===0?smooth((heroAge-.28)/.45):1;const shineStart=1.28,shineEnd=1.66,shineQ=rank===0?(heroAge-shineStart)/(shineEnd-shineStart):null;drawBadgeVisual(list[i],st.x+CARD_W/2,top,w,{blur,textAlpha,shineQ,shineOpacity:.32})}}
function steadyHero(list,off){let hero=-1,heroX=0;for(let i=4;i<list.length;i++){const x=10+i*PITCH-off;if(x<=HERO_TRIGGER_X){hero=i;heroX=x}else break}return {hero,heroX}}
function drawSteadyBadges(list,positions,sec,off){const {hero,heroX}=steadyHero(list,off);for(let i=0;i<Math.min(4,list.length);i++){const x=positions[i];if(x!=null&&x>-CARD_W&&x<W)drawBadgeVisual(list[i],x+CARD_W/2,tier(3).top,tier(3).w)}if(hero<4)return;const age=(HERO_TRIGGER_X-heroX)/STEADY_SPEED,duration=window.RIBBON_STEADY_BADGE?.tierDuration??.48,q=smooth(age/duration);for(let i=4;i<=hero;i++){const x=positions[i];if(x==null||x<-CARD_W||x>W)continue;const rank=hero-i,now=tier(rank),before=tier(Math.max(0,rank-1));let w,top;if(rank===0){w=now.w;top=sampledFallTop(age)}else{w=lerp(before.w,now.w,q);top=lerp(before.top,now.top,q)}const sc=window.RIBBON_STEADY_BADGE?.shine||{startAge:.60,endAge:1.17,opacity:.34};const shineQ=rank===0?(age-sc.startAge)/(sc.endAge-sc.startAge):null;drawBadgeVisual(list[i],x+CARD_W/2,top,w,{shineQ,shineOpacity:sc.opacity})}}
function openingCardState(i,sec){const targets=[10,487,964,1441];if(i===0){const q=outCubic((sec-.35)/1.05);return {visible:sec>.28,x:lerp(-390,targets[0],q)}}if(i===1){const q=outCubic((sec-2.28)/1.08);return {visible:sec>2.2,x:lerp(targets[1]-255,targets[1],q)}}if(i===2){const q=outCubic((sec-4.28)/1.12);return {visible:sec>4.2,x:lerp(targets[2]-245,targets[2],q)}}if(i===3){const q=outCubic((sec-6.42)/1.18);return {visible:sec>6.34,x:lerp(targets[3]+250,targets[3],q)}}return {visible:false,x:0}}
function openingCreditsX(sec){const inQ=outCubic((sec-.35)/1.05),base=lerp(2310,1441,inQ);if(sec<6.35)return base;return lerp(1441,1960,outCubic((sec-6.35)/1.2))}
const scrollKeys=[[8.70,0],[8.80,2.5],[8.90,9.7],[9.00,20.3],[9.10,32.3],[9.30,64.8],[9.50,103.8],[9.70,145],[9.90,191.8],[10.10,240.2],[10.30,285.8],[10.50,314.2]];
function scrollAt(sec){if(sec<=scrollKeys[0][0])return 0;for(let i=1;i<scrollKeys.length;i++){if(sec<=scrollKeys[i][0]){const [ta,da]=scrollKeys[i-1],[tb,db]=scrollKeys[i];return lerp(da,db,(sec-ta)/(tb-ta))}}return scrollKeys.at(-1)[1]+(sec-scrollKeys.at(-1)[0])*STEADY_SPEED}
function drawEndWipe(sec){if(sec<212.2)return;const q=clamp((sec-212.2)/.25);ctx.fillStyle='#111';ctx.fillRect(0,0,1440,Math.round(H*q))}
function render(ms){const sec=ms/1000,list=data();ctx.clearRect(0,0,W,H);ctx.fillStyle=BORDER;ctx.fillRect(0,0,W,H);if(sec<8.7){const states=[];drawCredit(openingCreditsX(sec));for(let i=0;i<Math.min(4,list.length);i++){const st=openingCardState(i,sec);states[i]=st;if(st.visible)drawCardBase(list[i],st.x)}drawOpeningBadges(list,states,sec)}else{const off=scrollAt(sec),positions=[];for(let i=0;i<list.length;i++){const x=10+i*PITCH-off;positions[i]=x;if(x>-CARD_W&&x<W+20)drawCardBase(list[i],x)}drawSteadyBadges(list,positions,sec,off)}drawEndWipe(sec);timeOut.textContent=sec.toFixed(3)+' s';scrub.value=Math.round(ms)}
function loop(now){if(!playing)return;let ms=t0+(now-wall0);if(ms>218732){ms=0;t0=0;wall0=now}render(ms);requestAnimationFrame(loop)}
play.onclick=()=>{playing=!playing;play.textContent=playing?'Pause':'Play';if(playing){t0=+scrub.value;wall0=performance.now();requestAnimationFrame(loop)}};reset.onclick=()=>{playing=false;play.textContent='Play';render(0)};scrub.oninput=()=>render(+scrub.value);dataEl.oninput=()=>render(+scrub.value);document.fonts?.ready.then(()=>render(0));render(0);