const c=document.querySelector('#c'),ctx=c.getContext('2d'),scrub=document.querySelector('#s'),timeOut=document.querySelector('#t'),dataEl=document.querySelector('#d'),play=document.querySelector('#p'),reset=document.querySelector('#r'),err=document.querySelector('#err');
const W=1920,H=1080,CARD_W=470,PITCH=477,ART_H=872,TITLE_Y=872,TITLE_H=92,DESC_Y=965,DESC_H=110,BORDER='#0b0b0b',TITLE_BG='rgb(242,242,242)',DESC_BG='rgb(100,97,88)',BADGE_RED='rgb(194,0,11)';
const sample=[
 {title:'In A Freezer',value:'50K',unit:'YEARS',description:'Freezing stops bacteria from moving, preserving your hand',art:'#218fce'},
 {title:"Mars' Atmosphere",value:'10K',unit:'YEARS',description:'Frozen, airless and bone-dry – it mummifies you',art:'#d9491d'},
 {title:'Outside A Plane Mid-Flight',value:'5K',unit:'YEARS',description:'Freezing wind slowly grinds the frozen flesh away',art:'#2b9ee3'},
 {title:'Toothpaste',value:'8',unit:'MONTHS',description:'Mild abrasives slowly wear the skin and flesh away',art:'#36a5de'},
 {title:"World's Spiciest Hot Sauce",value:'6',unit:'MONTHS',description:'Vinegar and chilli oils attack the skin barrier',art:'#31130f'},
 {title:'Salt Water',value:'5',unit:'MONTHS',description:'Salt and moisture gradually damage exposed tissue',art:'#218cc6'},
 {title:'Bleach',value:'4',unit:'MONTHS',description:'Strong oxidisers aggressively damage tissue',art:'#d4d6d8'},
 {title:'Boiling Water',value:'SECONDS',unit:'',description:'Extreme heat rapidly destroys exposed tissue',art:'#71b9dc'}
];
dataEl.value=JSON.stringify(sample,null,2);
let playing=false,wall0=0,t0=0;
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
const outCubic=v=>1-Math.pow(1-clamp(v),3);
const smooth=v=>{v=clamp(v);return v*v*(3-2*v)};
const lerp=(a,b,t)=>a+(b-a)*t;
function data(){try{err.textContent='';return JSON.parse(dataEl.value)}catch(e){err.textContent=e.message;return sample}}
function wrapText(text,maxWidth,maxLines=2){const words=String(text||'').split(/\s+/);const lines=[];let line='';for(const w of words){const test=line?line+' '+w:w;if(ctx.measureText(test).width<=maxWidth||!line)line=test;else{lines.push(line);line=w;if(lines.length===maxLines-1)break}}if(line&&lines.length<maxLines)lines.push(line);return lines}
function cardGradient(card,x){const g=ctx.createLinearGradient(x,0,x+CARD_W,ART_H);g.addColorStop(0,card.art||'#2689c7');g.addColorStop(1,shade(card.art||'#2689c7',-22));return g}
function shade(hex,amt){const m=/^#?([0-9a-f]{6})$/i.exec(hex);if(!m)return hex;let n=parseInt(m[1],16),r=clamp((n>>16)+amt,0,255),g=clamp(((n>>8)&255)+amt,0,255),b=clamp((n&255)+amt,0,255);return `rgb(${r},${g},${b})`}
function badgeStageWidth(sec){if(sec<2.25)return 332;if(sec<3.35)return lerp(332,298,outCubic((sec-2.25)/1.1));if(sec<4.25)return 298;if(sec<5.4)return lerp(298,273,outCubic((sec-4.25)/1.15));if(sec<6.3)return 273;if(sec<7.6)return lerp(273,248,outCubic((sec-6.3)/1.3));return 248}
function openingCardState(i,sec){const targets=[10,487,964,1441];if(i===0){const q=outCubic((sec-.35)/1.05);return {visible:sec>.28,x:lerp(-390,targets[0],q),badgeStart:.55}}
 if(i===1){const q=outCubic((sec-2.28)/1.08);return {visible:sec>2.2,x:lerp(targets[1]-255,targets[1],q),badgeStart:2.43}}
 if(i===2){const q=outCubic((sec-4.28)/1.12);return {visible:sec>4.2,x:lerp(targets[2]-245,targets[2],q),badgeStart:4.43}}
 if(i===3){const q=outCubic((sec-6.42)/1.18);return {visible:sec>6.34,x:lerp(targets[3]+250,targets[3],q),badgeStart:6.6}}
 return {visible:false,x:0,badgeStart:99}}
function openingCreditsX(sec){const inQ=outCubic((sec-.35)/1.05),base=lerp(1920+390,1441,inQ);if(sec<6.35)return base;return lerp(1441,1920+40,outCubic((sec-6.35)/1.2))}
const scrollKeys=[[8.70,0],[8.80,2.5],[8.90,9.7],[9.00,20.3],[9.10,32.3],[9.30,64.8],[9.50,103.8],[9.70,145.0],[9.90,191.8],[10.10,240.2],[10.30,285.8],[10.50,314.2]];
function scrollAt(sec){if(sec<=scrollKeys[0][0])return 0;for(let i=1;i<scrollKeys.length;i++){if(sec<=scrollKeys[i][0]){const [ta,da]=scrollKeys[i-1],[tb,db]=scrollKeys[i];return lerp(da,db,(sec-ta)/(tb-ta))}}return scrollKeys.at(-1)[1]+(sec-scrollKeys.at(-1)[0])*133.3}
function drawCredit(x){ctx.save();ctx.fillStyle='#202020';ctx.fillRect(x,5,CARD_W,1070);ctx.fillStyle='#fff';ctx.textAlign='center';ctx.font='500 19px Nunito,sans-serif';wrapCentered('The values presented are estimates\nfrom publicly available sources. Individual results may\nvary depending on concentration, temperature,\nexposure time, and other factors. Do not attempt\nany experiments.',x+CARD_W/2,26,26);ctx.strokeStyle='#ddd';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(x+58,200);ctx.lineTo(x+CARD_W-58,200);ctx.stroke();ctx.font='800 51px Nunito,sans-serif';ctx.fillText('Credits',x+CARD_W/2,307);ctx.font='700 24px Nunito,sans-serif';const lines=['Lead Research & Sourcing','Ahmed','','Independent Fact Check','Alex Lambert','','Lead Graphic Designer','Jack H','','Edit & Post-Production','Alex Pacheco','','Thumbnail Designer','Diego Garcia','','Video Idea & Quality Check','Ideaguys.co'];let y=370;for(const line of lines){if(!line){y+=16;continue}ctx.fillText(line,x+CARD_W/2,y);y+=31}ctx.font='500 12px Nunito,sans-serif';wrapCentered('DISCLAIMER:\nTHIS VIDEO IS BASED ON\nCOMMUNITY DISCUSSIONS\nAND RELEVANT SOURCES.',x+CARD_W/2,888,14);ctx.restore()}
function wrapCentered(text,x,y,lineHeight){for(const line of String(text).split('\n')){ctx.fillText(line,x,y);y+=lineHeight}}
function drawCard(card,x,sec,index,badgeStart){ctx.save();ctx.beginPath();ctx.rect(x,5,CARD_W,1070);ctx.clip();ctx.fillStyle=cardGradient(card,x);ctx.fillRect(x,5,CARD_W,ART_H-5);
 // rough illustration scaffolding only; source artwork is intentionally separate from renderer geometry.
 ctx.globalAlpha=.18;for(let k=0;k<7;k++){ctx.fillStyle=k%2?'#fff':'#000';ctx.beginPath();ctx.arc(x+55+k*66,500+(k%3)*58,55+(k%2)*25,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;
 ctx.fillStyle=TITLE_BG;ctx.fillRect(x,TITLE_Y,CARD_W,TITLE_H);ctx.fillStyle=DESC_BG;ctx.fillRect(x,DESC_Y,CARD_W,DESC_H);
 ctx.textAlign='center';ctx.textBaseline='alphabetic';ctx.fillStyle='#090909';ctx.font='900 42px Nunito,sans-serif';const titleLines=wrapText(card.title,CARD_W-30,2);const titleBase=titleLines.length===1?931:905;titleLines.forEach((ln,j)=>ctx.fillText(ln,x+CARD_W/2,titleBase+j*39));
 ctx.fillStyle='#fff';ctx.font='700 25px Nunito,sans-serif';const descLines=wrapText(card.description,CARD_W-50,2);const descBase=descLines.length===1?1028:1012;descLines.forEach((ln,j)=>ctx.fillText(ln,x+CARD_W/2,descBase+j*29));
 drawBadge(card,x,sec,index,badgeStart);ctx.restore();ctx.fillStyle=BORDER;ctx.fillRect(Math.round(x+CARD_W),0,7,H)}
function drawBadge(card,x,sec,index,badgeStart){if(sec<badgeStart)return;const age=sec-badgeStart,target=badgeStageWidth(sec);const entrance=outCubic(age/.82);const baseW=target+lerp(95,0,outCubic(age/1.15));const w=baseW,h=w*1.153;const cx=x+CARD_W/2,finalTop=66;const y=lerp(-h*.95,finalTop,entrance);ctx.save();ctx.shadowColor='rgba(0,0,0,.38)';ctx.shadowBlur=18;ctx.shadowOffsetY=10;const grad=ctx.createLinearGradient(cx-w/2,y,cx+w/2,y+h);grad.addColorStop(0,'#d0000e');grad.addColorStop(.55,BADGE_RED);grad.addColorStop(1,'#b5000a');ctx.fillStyle=grad;hex(cx,y,w,h);ctx.fill();ctx.shadowColor='transparent';
 const textFade=smooth((age-.38)/.5);if(textFade>0){ctx.save();ctx.globalAlpha=textFade;ctx.filter=`blur(${lerp(13,0,smooth((age-.42)/.62))}px)`;ctx.fillStyle='#fff';ctx.textAlign='center';ctx.textBaseline='middle';ctx.shadowColor='rgba(0,0,0,.40)';ctx.shadowBlur=7;ctx.shadowOffsetY=6;ctx.font=`900 ${Math.round(w*.27)}px Nunito,sans-serif`;ctx.fillText(String(card.value||''),cx,y+h*.43);ctx.font=`800 ${Math.round(w*.13)}px Nunito,sans-serif`;if(card.unit)ctx.fillText(String(card.unit),cx,y+h*.64);ctx.restore()}
 const shineQ=(age-1.02)/.5;if(shineQ>0&&shineQ<1){ctx.save();hex(cx,y,w,h);ctx.clip();ctx.translate(cx,y+h/2);ctx.rotate(.34);const sx=lerp(-w*1.1,w*1.1,smooth(shineQ));const sg=ctx.createLinearGradient(sx-34,0,sx+34,0);sg.addColorStop(0,'rgba(255,255,255,0)');sg.addColorStop(.5,'rgba(255,255,255,.30)');sg.addColorStop(1,'rgba(255,255,255,0)');ctx.fillStyle=sg;ctx.fillRect(-w,-h,w*2,h*2);ctx.restore()}ctx.restore()}
function hex(cx,y,w,h){ctx.beginPath();ctx.moveTo(cx,y);ctx.lineTo(cx+w/2,y+h*.25);ctx.lineTo(cx+w/2,y+h*.75);ctx.lineTo(cx,y+h);ctx.lineTo(cx-w/2,y+h*.75);ctx.lineTo(cx-w/2,y+h*.25);ctx.closePath()}
function render(ms){const sec=ms/1000,list=data();ctx.clearRect(0,0,W,H);ctx.fillStyle=BORDER;ctx.fillRect(0,0,W,H);if(sec<8.7){drawCredit(openingCreditsX(sec));for(let i=0;i<Math.min(4,list.length);i++){const st=openingCardState(i,sec);if(st.visible)drawCard(list[i],st.x,sec,i,st.badgeStart)}}else{const off=scrollAt(sec);for(let i=0;i<list.length;i++){const xx=10+i*PITCH-off;if(xx>CARD_W*-1&&xx<W+20)drawCard(list[i],xx,sec,i,-99)}}timeOut.textContent=sec.toFixed(3)+' s';scrub.value=Math.round(ms)}
function loop(now){if(!playing)return;let ms=t0+(now-wall0);if(ms>218732){ms=0;t0=0;wall0=now}render(ms);requestAnimationFrame(loop)}
play.onclick=()=>{playing=!playing;play.textContent=playing?'Pause':'Play';if(playing){t0=+scrub.value;wall0=performance.now();requestAnimationFrame(loop)}};reset.onclick=()=>{playing=false;play.textContent='Play';render(0)};scrub.oninput=()=>render(+scrub.value);dataEl.oninput=()=>render(+scrub.value);document.fonts?.ready.then(()=>render(0));render(0);